---
# tasks file for fail2ban

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: fail2ban

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: fail2ban

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: fail2ban
